production:
  payments_sync_pending:
    class: PaymentsSyncJob
    queue: default
    schedule: every 10 minutes

  carrier_payouts_sync:
    class: CarrierPayoutSyncJob
    queue: default
    schedule: every hour
